[default]

# 1 - DEFININDO A PROPRIEDADE DE BLUR
# (DESFOQUE DA IMAGEM COM O OBJETIVO DE REMOÇÃO DE RUÍDOS DA IMAGEM)
BLUR_KSIZE = [17, 17]

# 2 - DESVIO PADRÃO DO KERNEL AO LONGO DO EIXO X (DIREÇÃO HORIZONTAL)
STD_DEV_X_DIRECTION = 0

# 3 - DESVIO PADRÃO DO KERNEL AO LONGO DO EIXO Y (DIREÇÃO VERTICAL)
STD_DEV_Y_DIRECTION = 0

# 4 - DEFININDO A PROPRIEDADE DE THRESHOLD (LIMIAR)
# VALOR DE PIXEL QUE SERÁ CONVERTIDO, CASO O PIXEL ULTRAPASSE O LIMIAR
MAX_COLOR_VAL = 255

# 5 - TAMANHO DO KERNEL PARA THRESHOLD
THRESHOLD_KSIZE = 15

# 6 - VARIÁVEL QUE REPRESENTA A CONSTANTE UTILIZADA NOS MÉTODOS (SUBTRAÍDA DA MÉDIA OU MÉDIA PONDERADA)
SUBTRACT_FROM_MEAN = -2

[development]