[default]

# NOME DO MODELO
APPNAME = 'OCR_TABLES'

# DIRETÓRIO DE SAVE DOS LOGS
DIR_SAVE_LOGS = 'LOGS'

# ARQUIVO DE SAVE DOS LOGS - LOGGING
LOG_FILENAME = 'LOG_OCR_TABLES.log'

# LEVEL DE CRITICIDADE DO LOG A SER REGISTRADO
LOGLEVEL = 'DEBUG'
LOGLEVEL_FILE = 'DEBUG'
LOGLEVEL_CONSOLE = 'DEBUG'

FORMAT_TYPES_ACCEPTED = ["jpg", "png"]

# INICIANDO A VARIÁVEL DE LOGGERS
LOGGERS = {}

# 1 - DEFININDO A PROPRIEDADE DE BLUR
# (DESFOQUE DA IMAGEM COM O OBJETIVO DE REMOÇÃO DE RUÍDOS DA IMAGEM)
BLUR_KSIZE = [17, 17]

# 2 - DESVIO PADRÃO DO KERNEL AO LONGO DO EIXO X (DIREÇÃO HORIZONTAL)
STD_DEV_X_DIRECTION = 0

# 3 - DESVIO PADRÃO DO KERNEL AO LONGO DO EIXO Y (DIREÇÃO VERTICAL)
STD_DEV_Y_DIRECTION = 0

# 4 - DEFININDO A PROPRIEDADE DE THRESHOLD (LIMIAR)
# VALOR DE PIXEL QUE SERÁ CONVERTIDO, CASO O PIXEL ULTRAPASSE O LIMIAR
MAX_COLOR_VAL = 255

# 5 - TAMANHO DO KERNEL PARA THRESHOLD
THRESHOLD_KSIZE = 15

# 6 - VARIÁVEL QUE REPRESENTA A CONSTANTE UTILIZADA NOS MÉTODOS (SUBTRAÍDA DA MÉDIA OU MÉDIA PONDERADA)
SUBTRACT_FROM_MEAN = -2

# 7 - REALIZANDO O PARÂMETRO DA ESCALA
SCALE = 5

# 8 - DEFININDO O TAMANHO MIN DE ÁREA DA TABELA
MIN_TABLE_AREA = 1e5

# PARÂMETROS DO OCR - TESSERACT
TESSERACT_LANG = 'eng'
TESSERACT_PSM = '1'
TESSERACT_OEM = '3'

# PARÂMETRO DO TIPO DE RETORNO DO OCR
TIPO_OCR = "TEXTO"

# DEFINIÇÃO SE A EXTRAÇÃO DE TABELA É DESEJADA
VALIDATOR_EXTRACT_TABLE = true

# DIRETÓRIO PARA SAVE DAS TABELAS OBTIDAS
PREFIX_DIR_SAVE_RESULTS_TABLE = "RESULTADO_OCR_TABLES"

PATTERN_FATURAMENTO = 'R(\$|S)'

PATTERN_CNPJ = '[0-9]{2}(\.|,)?[0-9]{3}(\.|,)?[0-9]{3}\/?[0-9]{4}\-?[0-9]{2}'

PATTERN_ONLY_NUMBERS = '[^\d]'

# SELECIONA APENAS LETRAS, PONTOS, BARRAS, TRAÇOS E NÚMEROS
REGEX_ONLY_LETTERS_NUMBERS_DOT_BARS_DASHES_COMMA = '[^A-Za-z0-9\-.,\s\/]'

REGEX_DATE_VALID = '[1-2]\d{3}'

# PATTERNS PARA SELEÇÃO DO VALOR DE FATURAMENTO
PATTERN_FATURAMENTO_1 = '(,|\.|-)\d{1,2}$'

PATTERN_FATURAMENTO_2 = '\w\s\d{1,4}\s\w'

# DICIONÁRIO DE MESES
DICT_MONTHS_ABREV = {"JAN" = 1, "FEV" = 2, "MAR" = 3, "ABR" = 4, "MAI" = 5, "JUN" = 6, "JUL" = 7, "AGO" = 8, "SET" = 9, "OUT" = 10, "NOV" = 11, "DEZ" = 12}

DICT_MONTHS_COMPLETE = {"JANEIRO" = 1, "FEVEREIRO" = 2, "MARCO" = 3, "ABRIL" = 4, "MAIO" = 5, "JUNHO" = 6, "JULHO" = 7, "AGOSTO" = 8, "SETEMBRO" = 9, "OUTUBRO" = 10, "NOVEMBRO" = 11, "DEZEMBRO" = 12}

# INICIANDO OS PERCENTUAIS DE MATCH DEFAULT
DEFAULT_PERCENTUAL_MATCH = 60

# DEFININDO SE DEVE HAVER PRÉ PROCESSAMENTO DOS ITENS ANTES DO CÁLCULO DE SEMELHANÇA
DEFAULT_PRE_PROCESSING = false

# INICIANDO A VARIÁVEL QUE CONTÉM O LIMIT NA CHAMADA DE MÁXIMAS SIMILARIDADES
DEFAULT_LIMIT_RESULT_BEST_SIMILAR = 1

# DEFININDO SE O CNPJ DEVE POSSUIR APENAS NÚMEROS
CNPJ_ONLY_NUMBERS = true

[development]